# Generated by Django 3.1.1 on 2020-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='first-post'),
            preserve_default=False,
        ),
    ]
